database:
  host: localhost
  port: 5432
  username: admin
  password: admin123

api_keys:
  stripe: sk_live_51HxyzABCDEF123456789
  sendgrid: SG.abc123def456.xyz789

admin:
  username: admin
  password: admin
